### ISSUE TITLE
Incorrect instructions in walkthrough for curver 0.4.0

### ISSUE THREAD

**Issue by DuncanTurnerMathematics** [MarkCBell/curver#12]
_Description_
The walkthrough for curver suggests defining h=S('a_0.b_1'). The problem is that b_1 is undefined for the Surface S=curver.load(1, 2) 

**To Reproduce**
1. Go to 'Python 3.6.9 interactive mode'
2. Run the line >>> S = curver.load(1, 2)
3. Run the line >>> h = S('a_0.b_1')
4. See error ValueError: After extracting ['a_0'], the remaining "b_1" of "a_0.b_1" could not be decomposed

**Expected behavior**
The example calculation to have well-defined arguments e.g. instead of suggesting a_0,b_1 where b_1 is undefined suggest the calculation h=S('a_0.b_0') where both a_0 and b_0 are defined

**Screenshots**
![Screenshot from 2020-06-09 18-21-11](https://user-images.githubusercontent.com/66691208/84179848-785a3380-aa7e-11ea-8755-7a2fae82cdc5.png)

**Desktop (please complete the following information):**
 - OS: Linux 
Linux project-ebd22b5d-4489-4dfc-b733-aef95a3b52f3 4.15.0-1037-gcp #39-Ubuntu SMP Wed Jul 3 06:28:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Browser - Chrome
 - Chrome Version 83

**Comment by MarkCBell** [comment]
Thanks for spotting this. Yes, you are right the example should be `h = S('a_0.b_0')`. I've updated the source documentation at https://curver.readthedocs.io/en/master/user/walkthrough.html and the updated documentation will be included in the next pypi release.
